owner: dioptra-io 
repo: iris-uptime

sites:
  - name: Iris Production API
    url: https://api.iris.dioptra.io/docs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /iris-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Iris Upptime
  introTitle: "Uptime monitoring of Iris platform"
  introMessage: This is the monitoring of Iris platform using [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dioptra-io/iris
