owner: dioptra-io 
repo: iris-uptime

sites:
  - name: Iris Website
    url: https://iris.dioptra.io
  - name: Iris Production API
    url: https://api.iris.dioptra.io/docs
  - name: Iris Development API
    url: https://api.dev.iris.dioptra.io/status

assignees: 
  - matthieugouel
  - maxmouchet

status-website:
  baseUrl: /iris-uptime
  logoUrl: https://raw.githubusercontent.com/dioptra-io/iris-website/main/src/assets/images/dioptra-logo.svg
  theme: night
  name: Dioptra Data | Iris Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dioptra-io/iris
