owner: dioptra-io 
repo: iris-upptime

sites:
  - name: Iris Production API
    url: https://api.iris.dioptra.io/docs
  - name: Iris Development API
    url: https://api.iris.dioptra-sandbox.xyz/docs

assignees: 
  - matthieugouel
  - maxmouchet

status-website:
  baseUrl: /iris-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Iris Upptime
  introTitle: "Uptime monitoring of Iris platform"
  introMessage: This is the monitoring of Iris platform using [upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dioptra-io/iris
